easy_admin:
    site_name: 'Roulette Admin'
    entities:
        User:
          class: App\Entity\User
        Article:
          class: App\Entity\Article
          list:
              fields: ['id', 'title', 'content', 'createdAt', 'img']
          form:  # <-- 'form' is applied to both 'new' and 'edit' views
            fields:
                - { property: 'title', type: 'text', label: 'Titre' }
                - { property: 'content', type: 'text', label: 'Contenu2', css_class: 'markDown' }
                - { property: 'createdAt', type: 'datetime', label: 'Date' }
                - { property: 'img', type: 'text', label: 'Lien Image' }
                - { property: 'author', type_options: { expanded: false, multiple: false }, label: 'Auteur' }
        Comment:
          class: App\Entity\Comment
    design:
      assets:
        js:
          - 'https://unpkg.com/snarkdown@1.2.2/dist/snarkdown.umd.js'
          - 'js/custom_markdown.js'
          - 'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-markdown-editor/2.0.2/js/bootstrap-markdown-editor.js'
          - 'http://cdnjs.cloudflare.com/ajax/libs/ace/1.1.3/ace.js'
        css:
          - 'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-markdown-editor/2.0.2/css/bootstrap-markdown-editor.css'
          - 'css/bootstrap.min.css'