easy_admin:
    site_name: 'Roulette Admin'
    entities:
        User:
          class: App\Entity\User
        Article:
          class: App\Entity\Article
          list:
              fields: ['id', 'title', 'content', 'createdAt', 'img']
          form:  # <-- 'form' is applied to both 'new' and 'edit' views
            fields:
                - { property: 'title', type: 'text', label: 'Titre' }
                - { property: 'content', type: 'text', label: 'Contenu', css_class: 'input-large' }
                - { property: 'createdAt', type: 'datetime', label: 'Date' }
                - { property: 'img', type: 'text', label: 'Lien Image' }
                - { property: 'author', type_options: { expanded: false, multiple: false }, label: 'Auteur' }
        Comment:
          class: App\Entity\Comment