miser:
    path: /miser
    controller: App\Controller\MiseController::miser

check_gain:
    path: /check
    controller: App\Controller\MiseController::checkGain

histo:
    path: /histo
    controller: App\Controller\MiseController::historique