index:
    path: /
    controller: App\Controller\BlogController::index

#contact:
  #path:       /{_locale}/
  #controller: App\Controller\ContactController::index
  #requirements:
    #_locale: en|fr|de