<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMoPeNlE\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMoPeNlE/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMoPeNlE.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMoPeNlE\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMoPeNlE\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'MoPeNlE',
    'container.build_id' => '235b7332',
    'container.build_time' => 1555403961,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMoPeNlE');
