<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTHwBwDa\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTHwBwDa/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTHwBwDa.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTHwBwDa\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTHwBwDa\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'THwBwDa',
    'container.build_id' => '60b01f45',
    'container.build_time' => 1555401801,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTHwBwDa');
